name: keycloak-with-attributes-verification

services:

  mysql:
    image: mysql:8
    restart: unless-stopped
    environment:
      # The user, password and database that Keycloak
      # is going to create and use
      MYSQL_USER: keycloak_user
      MYSQL_PASSWORD: keycloak_password
      MYSQL_DATABASE: keycloak_db
      # Self-Explanatory
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - keycloak-and-mysql-volume:/var/lib/mysql
    networks:
      - keycloak-and-mysql-network

  keycloak:
    image: keycloak-with-attributes-verification
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8081:8080
    restart: unless-stopped
    environment:
      # User and password for the Administration Console
      KEYCLOAK_ADMIN: kc_admin_user
      KEYCLOAK_ADMIN_PASSWORD: kc_admin_password
      # DB connection
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://mysql:3306/keycloak_db
      KC_DB_USERNAME: keycloak_user
      KC_DB_PASSWORD: keycloak_password
    volumes:
      - ./themes:/opt/keycloak/themes
    command:
      - start 
      - --http-enabled=true
      - --proxy-headers=forwarded
      - --hostname-strict=false
      - --hostname-debug=true
    depends_on:
      - mysql
    networks:
      - keycloak-and-mysql-network

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8082:80
    environment:
      PMA_HOST: mysql
      PMA_USER: keycloak_user
      PMA_PASSWORD: keycloak_password
    depends_on:
      - mysql
    networks:
      - keycloak-and-mysql-network

networks:
  keycloak-and-mysql-network:

volumes:
  keycloak-and-mysql-volume:
